In [53]:
import pandas as pd

In [54]:
import numpy as np

In [55]:
df = pd.read_csv(r'https://raw.githubusercontent.com/Sarvesh-S-Patil/Dataset/main/Diabetes.csv')

In [56]:
df.head()

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
0            6      148         72       35        0  33.6  0.627   50   
1            1       85         66       29        0  26.6  0.351   31   
2            8      183         64        0        0  23.3  0.672   32   
3            1       89         66       23       94  28.1  0.167   21   
4            0      137         40       35      168  43.1  2.288   33   

   diabetes  
0         1  
1         0  
2         1  
3         0  
4         1

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   pregnancies  768 non-null    int64  
 1   glucose      768 non-null    int64  
 2   diastolic    768 non-null    int64  
 3   triceps      768 non-null    int64  
 4   insulin      768 non-null    int64  
 5   bmi          768 non-null    float64
 6   dpf          768 non-null    float64
 7   age          768 non-null    int64  
 8   diabetes     768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [58]:
df.describe()

pregnancies     glucose   diastolic     triceps     insulin  \
count   768.000000  768.000000  768.000000  768.000000  768.000000   
mean      3.845052  120.894531   69.105469   20.536458   79.799479   
std       3.369578   31.972618   19.355807   15.952218  115.244002   
min       0.000000    0.000000    0.000000    0.000000    0.000000   
25%       1.000000   99.000000   62.000000    0.000000    0.000000   
50%       3.000000  117.000000   72.000000   23.000000   30.500000   
75%       6.000000  140.250000   80.000000   32.000000  127.250000   
max      17.000000  199.000000  122.000000   99.000000  846.000000   

              bmi         dpf         age    diabetes  
count  768.000000  768.000000  768.000000  768.000000  
mean    31.992578    0.471876   33.240885    0.348958  
std      7.884160    0.331329   11.760232    0.476951  
min      0.000000    0.078000   21.000000    0.000000  
25%     27.300000    0.243750   24.000000    0.000000  
50%     32.000000    0.372500   29.000000    0.000000  
75%     36.600000    0.626250   41.000000    1.000000  
max     67.100000    2.420000   81.000000    1.000000

In [59]:
df.columns

Index(['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age', 'diabetes'],
      dtype='object')

In [60]:
df.shape

(768, 9)

In [61]:
df['diabetes'].value_counts()

0    500
1    268
Name: diabetes, dtype: int64

In [62]:
df.groupby('diabetes').mean()

pregnancies     glucose  diastolic    triceps     insulin  \
diabetes                                                              
0            3.298000  109.980000  68.184000  19.664000   68.792000   
1            4.865672  141.257463  70.824627  22.164179  100.335821   

                bmi       dpf        age  
diabetes                                  
0         30.304200  0.429734  31.190000  
1         35.142537  0.550500  37.067164

In [63]:
y=df['diabetes']

In [64]:
y.shape

(768,)

In [65]:
X=df.drop(['diabetes'],axis=1)

In [66]:
X.shape

(768, 8)

In [67]:
X

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age
0              6      148         72       35        0  33.6  0.627   50
1              1       85         66       29        0  26.6  0.351   31
2              8      183         64        0        0  23.3  0.672   32
3              1       89         66       23       94  28.1  0.167   21
4              0      137         40       35      168  43.1  2.288   33
..           ...      ...        ...      ...      ...   ...    ...  ...
763           10      101         76       48      180  32.9  0.171   63
764            2      122         70       27        0  36.8  0.340   27
765            5      121         72       23      112  26.2  0.245   30
766            1      126         60        0        0  30.1  0.349   47
767            1       93         70       31        0  30.4  0.315   23

[768 rows x 8 columns]

In [68]:
from sklearn.preprocessing import MinMaxScaler

In [69]:
mm = MinMaxScaler()

In [70]:
X= mm.fit_transform(X)

In [71]:
X

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

In [72]:
from sklearn.model_selection import train_test_split 

In [73]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3 , random_state =2529 )

In [74]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape


((537, 8), (231, 8), (537,), (231,))

In [75]:
from sklearn.linear_model import LogisticRegression

In [76]:
lr= LogisticRegression()

In [77]:
lr.fit(X_train,y_train)

LogisticRegression()

In [78]:
y_pred= lr.predict(X_test)

In [79]:
y_pred.shape

(231,)

In [80]:
y_pred

array([0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1])

In [81]:
lr.predict_proba(X_test)

array([[0.87946998, 0.12053002],
       [0.59958843, 0.40041157],
       [0.33869015, 0.66130985],
       [0.70625215, 0.29374785],
       [0.55893242, 0.44106758],
       [0.36724463, 0.63275537],
       [0.16360933, 0.83639067],
       [0.30066834, 0.69933166],
       [0.91142377, 0.08857623],
       [0.49981736, 0.50018264],
       [0.92067479, 0.07932521],
       [0.27488402, 0.72511598],
       [0.75356548, 0.24643452],
       [0.92015134, 0.07984866],
       [0.81541256, 0.18458744],
       [0.47341943, 0.52658057],
       [0.37791835, 0.62208165],
       [0.55553959, 0.44446041],
       [0.89719093, 0.10280907],
       [0.81016432, 0.18983568],
       [0.46241262, 0.53758738],
       [0.46405765, 0.53594235],
       [0.72861372, 0.27138628],
       [0.93939119, 0.06060881],
       [0.79376047, 0.20623953],
       [0.80186616, 0.19813384],
       [0.73978527, 0.26021473],
       [0.51847931, 0.48152069],
       [0.88234404, 0.11765596],
       [0.69813424, 0.30186576],
       [0.

In [82]:
from sklearn.metrics import confusion_matrix,classification_report

In [83]:
print(confusion_matrix(y_test,y_pred))

[[133  12]
 [ 46  40]]


In [84]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.74      0.92      0.82       145
           1       0.77      0.47      0.58        86

    accuracy                           0.75       231
   macro avg       0.76      0.69      0.70       231
weighted avg       0.75      0.75      0.73       231



In [85]:
X_new = df.sample(1)

In [86]:
X_new


pregnancies  glucose  diastolic  triceps  insulin   bmi   dpf  age  \
96            2       92         62       28        0  31.6  0.13   24   

    diabetes  
96         0

In [87]:
X_new.shape

(1, 9)

In [88]:
X_new = X_new.drop(['diabetes'],axis =1)

In [89]:
X_new

pregnancies  glucose  diastolic  triceps  insulin   bmi   dpf  age
96            2       92         62       28        0  31.6  0.13   24

In [90]:
X_new.shape

(1, 8)

In [91]:
X_new = mm.fit_transform(X_new)

In [92]:
y_pred_new = lr.predict(X_new)

In [93]:
y_pred_new

array([0])

In [94]:
lr.predict_proba(X_new)

array([[0.9928188, 0.0071812]])

In [95]:
## Actual and Predicted Class is 0 that is Non-Diabetic